/-
Copyright 2026 Craig Tiller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import Lean
import Gasm.Core.Types
import Gasm.Core.Verification
import Gasm.Effects.Trace
import Gasm.Effects.Network
import Gasm.Effects.Console
import Gasm.Effects.Process
import Gasm.Targets.X86_64.Instructions.Base
import Gasm.Targets.X86_64.Semantics
import Gasm.Targets.Windows.PEFormat
import Gasm.Targets.Windows.Linker
import Gasm.Targets.Windows.Win32API
import Gasm.Targets.Linux.Syscall
import Gasm.Targets.Linux.Linker
import Gasm.Targets.WASI.ABI
import Spikes.Spike4HttpServer.Spec
import Spikes.Spike4HttpServer.Windows.Program
import Spikes.Spike4HttpServer.Linux.Program
import Spikes.Spike4HttpServer.Wasm.Program

namespace Spikes.Spike4HttpServer

open Gasm.Core
open Gasm.Core.Verification
open Gasm.Effects
open Gasm.Targets.X86_64
open Gasm.Targets.Windows
open Gasm.Targets.Linux
open Gasm.Targets.WASI
open Spikes.Spike4HttpServer.Wasm

set_option maxRecDepth 2000000
set_option maxHeartbeats 4000000

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Pure canonical effect trace generated by high-level monadic HTTP 1.1 server specification for Root (/). -/
def modelTraceRoot : List AnyEvent :=
  canonicalServerTrace

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Pure canonical effect trace generated by high-level monadic HTTP 1.1 server specification for /status. -/
def modelTraceStatus : List AnyEvent :=
  canonicalStatusServerTrace

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Pure canonical effect trace generated by high-level monadic HTTP 1.1 server specification for 404. -/
def modelTrace404 : List AnyEvent :=
  canonical404ServerTrace

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Windows x86_64 concrete machine execution trace on Root (/) request. -/
def windowsTraceRoot : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests ["GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Windows x86_64 concrete machine execution trace on /status request. -/
def windowsTraceStatus : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests ["GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Windows x86_64 concrete machine execution trace on 404 request. -/
def windowsTrace404 : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests ["GET /unknown HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- WebAssembly WASI execution trace on Root (/) request. -/
def wasmTraceRoot : List AnyEvent :=
  runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"]

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- WebAssembly WASI execution trace on /status request. -/
def wasmTraceStatus : List AnyEvent :=
  runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"]

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- WebAssembly WASI execution trace on 404 request. -/
def wasmTrace404 : List AnyEvent :=
  runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET /unknown HTTP/1.1\r\nHost: localhost\r\n\r\n"]

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Windows Machine matches High-Level Spec on Root (/) route. -/
theorem spike4_windows_root_trace_equivalence :
    (windowsTraceRoot == modelTraceRoot) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Windows Machine matches High-Level Spec on /status route. -/
theorem spike4_windows_status_trace_equivalence :
    (windowsTraceStatus == modelTraceStatus) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Windows Machine matches High-Level Spec on 404 Not Found route. -/
theorem spike4_windows_404_trace_equivalence :
    (windowsTrace404 == modelTrace404) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: WebAssembly WASI matches High-Level Spec on Root (/) route. -/
theorem spike4_wasm_root_trace_equivalence :
    (wasmTraceRoot == modelTraceRoot.map Inject.inject) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: WebAssembly WASI matches High-Level Spec on /status route. -/
theorem spike4_wasm_status_trace_equivalence :
    (wasmTraceStatus == modelTraceStatus.map Inject.inject) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: WebAssembly WASI matches High-Level Spec on 404 Not Found route. -/
theorem spike4_wasm_404_trace_equivalence :
    (wasmTrace404 == modelTrace404.map Inject.inject) = true := by
  native_decide

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Linux x86_64 concrete machine execution trace on Root (/) request. -/
def linuxTraceRoot : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Spikes.Spike4HttpServer.Linux.spike4Instructions (Spikes.Spike4HttpServer.Linux.spike4Executable.loadWithRequests ["GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Linux x86_64 concrete machine execution trace on /status request. -/
def linuxTraceStatus : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Spikes.Spike4HttpServer.Linux.spike4Instructions (Spikes.Spike4HttpServer.Linux.spike4Executable.loadWithRequests ["GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- Linux x86_64 concrete machine execution trace on 404 request. -/
def linuxTrace404 : List AnyEvent :=
  runAsmTrace (Event := AnyEvent) Spikes.Spike4HttpServer.Linux.spike4Instructions (Spikes.Spike4HttpServer.Linux.spike4Executable.loadWithRequests ["GET /unknown HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Linux Machine matches High-Level Spec on Root (/) route. -/
theorem spike4_linux_root_trace_equivalence :
    (linuxTraceRoot == modelTraceRoot) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Linux Machine matches High-Level Spec on /status route. -/
theorem spike4_linux_status_trace_equivalence :
    (linuxTraceStatus == modelTraceStatus) = true := by
  native_decide

/- REF: docs/REVIEW.md#42-pillar-2-semantic-integrity-adversarial-domain-gap-hunting -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Constructive Proof: x86_64 Linux Machine matches High-Level Spec on 404 Not Found route. -/
theorem spike4_linux_404_trace_equivalence :
    (linuxTrace404 == modelTrace404) = true := by
  native_decide

-- REF: wasm-exec-runtime#administrative-instructions -- Fuel-safety witnesses (see the identical
-- checks and their rationale in Spikes/Spike1Hello/Wasm/Equivalence.lean), one per Spike 4 WASI
-- route exercised above: proves each actual run never exhausts `defaultWasmFuel` under
-- `runWasiTraceState`, rather than merely assuming it.
#guard !Gasm.Targets.Wasm.WasmRunResult.isError
  (runWasiTraceState spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"])
#guard !Gasm.Targets.Wasm.WasmRunResult.isError
  (runWasiTraceState spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"])
#guard !Gasm.Targets.Wasm.WasmRunResult.isError
  (runWasiTraceState spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports ["GET /unknown HTTP/1.1\r\nHost: localhost\r\n\r\n"])

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- **Domain-honesty note (PA17).** The real per-connection domain Law 9's read-binder clause
    demands here is `∀ (request : ByteArray)` (or the `String` `recv`/`sock_recv` currently model
    as their unit of transfer) -- any byte string a client can send, per
    `docs/READ_BINDER_CONTRACT.md`. `HttpRoute` below is NOT that domain: it is a
    three-element proxy standing in for exactly the three literal request strings
    `routeRequestStr` maps it to, chosen so `∀ (r : HttpRoute)` type-checks trivially over a
    domain of size 3. The historical Law 9 mock-verification census classified
    the `cases r; exact ...` composition below as "Tier 3 -- legit pattern," reasoning that it is
    a genuine finite-∀ over an exhaustive enum. **That reasoning is correct about the outer
    composition and incomplete about the inner claim**: each of the three branches is still one
    `native_decide` check against one literal byte string, not "any request that would route the
    same way." The historical route-prefix counterexamples were fixed by N8 (see the FIXED note
    below), but the domain gap is still substantive: malformed request lines that the model maps
    to 400 Bad Request receive a different response from at least one lowering. The checked
    surviving counterexamples are listed under `spike4GeneralClaimCounterexamples` below.
    `spike4_windows_trace_equivalence_for_request` and
    `spike4_wasm_trace_equivalence_for_request` below restate the six facts this file already
    proves with their real, narrow domain (one of three literal request strings) made an
    explicit, checkable hypothesis instead of an implicit `HttpRoute` case split. They do not
    extend coverage to arbitrary request bytes; the fully general claim remains false on the
    malformed-request witnesses. -/
inductive HttpRoute where
  | root
  | status
  | notFound

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#11-supported-http-11-specification-subset -/
/-- Maps routing enum to raw HTTP request text. -/
def routeRequestStr : HttpRoute → String
  | .root => "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"
  | .status => "GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"
  | .notFound => "GET /unknown HTTP/1.1\r\nHost: localhost\r\n\r\n"

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#11-supported-http-11-specification-subset -/
/-- Maps routing enum to expected high-level monadic trace. -/
def routeModelTrace : HttpRoute → List AnyEvent
  | .root => modelTraceRoot
  | .status => modelTraceStatus
  | .notFound => modelTrace404

/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Universal routing equivalence theorem on x86_64 Windows across all route branches. -/
theorem spike4_windows_route_equivalence (r : HttpRoute) :
    (runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests [routeRequestStr r]) == routeModelTrace r) = true := by
  cases r
  · exact spike4_windows_root_trace_equivalence
  · exact spike4_windows_status_trace_equivalence
  · exact spike4_windows_404_trace_equivalence

/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Universal routing equivalence theorem on WebAssembly WASI across all route branches. -/
theorem spike4_wasm_route_equivalence (r : HttpRoute) :
    (runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports [routeRequestStr r] == (routeModelTrace r).map Inject.inject) = true := by
  cases r
  · exact spike4_wasm_root_trace_equivalence
  · exact spike4_wasm_status_trace_equivalence
  · exact spike4_wasm_404_trace_equivalence

/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Universal routing equivalence theorem on x86_64 Linux across all route branches. -/
theorem spike4_linux_route_equivalence (r : HttpRoute) :
    (runAsmTrace (Event := AnyEvent) Linux.spike4Instructions (Linux.spike4Executable.loadWithRequests [routeRequestStr r]) == routeModelTrace r) = true := by
  cases r
  · exact spike4_linux_root_trace_equivalence
  · exact spike4_linux_status_trace_equivalence
  · exact spike4_linux_404_trace_equivalence

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Honest restatement of `spike4_windows_route_equivalence`'s three constituent facts with their
    real, narrow domain (one of the three literal request strings `routeRequestStr` produces) made
    an explicit, machine-checked hypothesis (`h`) rather than an implicit `HttpRoute` case split
    standing in for it -- the domain-honesty shape `docs/SPIKES/SPIKE4_HTTP_SERVER.md` §4 records
    when a genuinely universal `∀ (request : ByteArray)` statement is not reachable in this task:
    "for all inputs satisfying P, with P stated." `P` here is deliberately narrow and is not the
    real per-route domain (see the surviving general-claim counterexamples below, which is why it
    cannot honestly be widened to arbitrary request bytes). -/
theorem spike4_windows_trace_equivalence_for_request (req : String) (r : HttpRoute)
    (h : req = routeRequestStr r) :
    (runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests [req]) == routeModelTrace r) = true := by
  subst h
  exact spike4_windows_route_equivalence r

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Honest restatement of `spike4_wasm_route_equivalence`'s three constituent facts; see
    `spike4_windows_trace_equivalence_for_request` immediately above for the rationale, which
    applies identically here. -/
theorem spike4_wasm_trace_equivalence_for_request (req : String) (r : HttpRoute)
    (h : req = routeRequestStr r) :
    (runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports [req] == (routeModelTrace r).map Inject.inject) = true := by
  subst h
  exact spike4_wasm_route_equivalence r

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/- REF: docs/EQUIVALENCE_PROOFS.md#1-mathematical-formulation-of-equivalence -/
/-- Honest restatement of `spike4_linux_route_equivalence`'s three constituent facts; see
    `spike4_windows_trace_equivalence_for_request` above for the rationale, which applies
    identically here. Parity fix: the original PA17 pass added this wrapper for Windows and Wasm
    but not Linux, even though `spike4_linux_route_equivalence` (above) has the identical
    `HttpRoute`-proxy-domain shape and the identical "not the real per-request domain" caveat. -/
theorem spike4_linux_trace_equivalence_for_request (req : String) (r : HttpRoute)
    (h : req = routeRequestStr r) :
    (runAsmTrace (Event := AnyEvent) Linux.spike4Instructions (Linux.spike4Executable.loadWithRequests [req]) == routeModelTrace r) = true := by
  subst h
  exact spike4_linux_route_equivalence r

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-!
**FIXED (N8).** This note used to document a confirmed route-prefix-confusion divergence between
`spike4_windows_route_equivalence`/`spike4_wasm_route_equivalence` and the honest per-request model
(`Spec.lean`'s `parseRequestLine`/`routeRequest`); `docs/SPIKES/SPIKE4_HTTP_SERVER.md`
fixed the underlying assembly/WASI dispatch bug, and the regression suite below (`spike4RouteFixedOnAllTargets`)
re-checks every witness this note used to name. The historical bug, for the record:

- **Windows and Linux** (`Spikes/Spike4HttpServer/{Windows,Linux}/Program.lean`, the `send_status`
  check): the route dispatch loaded 8 bytes at the request buffer's offset 4 and masked to 5 bytes
  (`0xFFFFFFFFFF`), comparing against `"/stat"` (`0x746174732F`) — so any path merely starting with
  `/stat` (`"/static"`, `"/status_check"`, `"/statx"`, ...) was misrouted to the 200 OK status
  handler instead of Spec's 404. Both targets ran the identical routing bytes, so the bug was not
  Windows-specific despite the task that found it inspecting only the Windows lowering.
- **WebAssembly** (`Spikes/Spike4HttpServer/Wasm/Program.lean`, step 4): the route dispatch read a
  *single* byte at offset `0x405` (immediately after the path's leading `/`) and matched `/status`
  whenever that one byte was `'s'` — strictly weaker than the 5-byte prefix bug above, misrouting
  any path merely starting with `s` (`"/search"`, `"/shop"`, `"/settings"`, even the bare `"/s"`).

**The fix** (REF: `Spikes/Spike4HttpServer/Windows/Program.lean`,
`Spikes/Spike4HttpServer/Linux/Program.lean`, `Spikes/Spike4HttpServer/Wasm/Program.lean`): all
three targets now compare the *full* 8 bytes at the path's start against `"/status "` (the 7
characters plus the request-line's mandatory delimiting space) with no masking — an exact match on
the whole path token rather than a prefix, so no string that is merely `/status`-prefixed can match
without literally being `/status`. `spike4RouteFixedOnAllTargets` below re-checks this against
`serverModelTraceFor` (the honest model) for every witness path this note used to name as broken.

**What N8 did *not* make provable, and why (still true post-fix; PA17's point stands).** The six
`spike4_{windows,wasm}_{root,status,404}_trace_equivalence` theorems above remain one
`native_decide` check against one literal request string per route — `HttpRoute` is a 3-element
proxy for "which route", not the real `∀ (request : ByteArray)` domain a server's correctness claim
needs (PA17's finding, independent of whether the routing bytes are correct). The regression checks
below strengthen empirical confidence by exercising many more concrete requests than those six ever
did, including every literal counterexample this note previously named, but they are still pointwise
`native_decide`/`#guard` checks, not a structural induction over arbitrary byte strings — reaching
that (PA17's "real prize") requires PA6's read-binder contract and PA7's reactive-program contract to
land first, per PA17's own sequencing (`after: [PA7, PA8]`), and is out of N8's scope. Two further
gaps neither N8 nor this file's regression suite closes: (1) `parseRequestLine` returns `none` (400
Bad Request) for any request line that isn't exactly three space-separated tokens, a response class
neither lowering can ever emit — so a fully universal `∀ (request : ByteArray)` claim is false for
this reason alone, independent of routing correctness; (2) the memory-safety half of N8 (the
recv-length validation below) is provably absent from a *real* buffer-overflow/EOF-crash standpoint
by inspection of the assembly, but not provable as a trace-equivalence fact in this model, for the
reason the next paragraph explains.

**Why the recv-length-validation fix (N8 defect 2) isn't checked against the honest model here.**
`Win32API.lean`'s `recvHook`, `Syscall.lean`'s `sysReadHook`, and `TraceM`'s own
`MonadNetwork.recv` (`Gasm/Effects/Trace.lean`) all return `some req` — never `none` — for every
element already present in `incomingRequests`, *including the empty string*; `none` only occurs
once the whole request list is exhausted. So while this repository's fixed assembly now closes the
connection without sending anything when `recv`/`read` returns `0` (see `spike4EmptyRecvClosesWithoutCorruption`
below), the *honest* `httpServerMonadic` model treats an empty-string request exactly like any
other: `parseRequestLine ""` fails to split into three tokens and the model sends a 400 Bad Request
before closing. These two behaviors are genuinely different, not because the fix is wrong, but
because `MonadNetwork.recv` cannot represent a true zero-byte/EOF read distinctly from "one more
(possibly empty) logical request" — the same "vacuous ∀ proven against a model that cannot produce
the input the claim needs to range over" gap `docs/READ_BINDER_CONTRACT.md` names for
short/partial reads (`docs/READ_BINDER_CONTRACT.md`), recurring here one layer down (read *atomicity*, not read
*length*). `spike4EmptyRecvClosesWithoutCorruption` below instead pins the fixed assembly's *own*
observable behavior (a regression check, not a spec-equivalence claim) and confirms the connection
immediately after it is unaffected.
-/

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md -/
/-- Combined route-correctness regression check across all three lowered targets for one request
    string, verified against the honest per-request model (`serverModelTraceFor`, `Spec.lean`).
    Used below to re-check every literal counterexample the (now-fixed) route-prefix bug's
    "KNOWN DIVERGENCE" note used to name, so the bug documented above cannot silently return on any
    target. -/
def spike4RouteFixedOnAllTargets (req : String) : Bool :=
  let expected := serverModelTraceFor req
  (runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests [req]) == expected) &&
  (runAsmTrace (Event := AnyEvent) Linux.spike4Instructions (Linux.spike4Executable.loadWithRequests [req]) == expected) &&
  (runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports [req] == expected.map Inject.inject)

-- Every prefix-confusion witness the pre-fix "KNOWN DIVERGENCE" note named, plus the two
-- specifically called out in docs/SPIKES/SPIKE4_HTTP_SERVER.md's routing-bug writeup.
#guard spike4RouteFixedOnAllTargets "GET /static HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /search HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /status_check HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /statx HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /statuses HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /s HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /shop HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GET /settings HTTP/1.1\r\nHost: localhost\r\n\r\n"
-- The one path that *should* still route to /status: the exact string, confirming the fix isn't
-- an over-correction that broke the legitimate case.
#guard spike4RouteFixedOnAllTargets "GET /status HTTP/1.1\r\nHost: localhost\r\n\r\n"

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#11-supported-http-11-specification-subset -/
/-!
## Method validation (PA17's second defect -- FIXED on all three targets)

Before this change **no** Spike 4 lowering validated the HTTP method. All three assumed, with no
check at all, that the four bytes at the start of a received request were literally `"GET "`, and
read the routing window at the fixed offset 4. Two consequences, both real divergences from the
honest model (`Spec.lean`'s `parseRequestLine`, delegating to the proven
`Stdlib.Http11.parseRequestLine`):

1. **An invalid method was answered as if it were `GET`.** `"FOO / HTTP/1.1..."` is rejected by the
   model with 400 Bad Request (`FOO` is not one of `Stdlib.Http11.Method`'s nine constructors), but
   because `"FOO "` is also four bytes the fixed offset-4 read landed on the request's genuine
   `"/ "` target and every target answered 200 OK. This is the divergence
   `witnessMethodNotValidatedDivergence` below was introduced to witness; it is now a *passing*
   regression vector, which is the flip this fix had to produce.
2. **A valid non-three-character method mis-read the path.** `Spec.routeRequest` dispatches purely
   on the target, so the model answers `"POST / HTTP/1.1..."` with the same 200 root response it
   gives `"GET / ..."`. The lowerings' fixed offset 4 landed mid-token for `HEAD`/`POST` (offset 5),
   `TRACE`/`PATCH` (6), `DELETE` (7) and `CONNECT`/`OPTIONS` (8), so all seven of those methods were
   silently misrouted -- a divergence class the pre-fix witness did not name and no test covered.

**The fix** (`Spikes/Spike4HttpServer/MethodDispatch.lean` for the two x86-64 targets,
`Spikes/Spike4HttpServer/Wasm/Program.lean`'s `wasmMethodValidationInstrs` for WASI): each target
now tests the leading request bytes, masked to each token's own length, against every
`Stdlib.Http11.Method` token plus the request line's mandatory delimiting SP, and takes the routing
window at the offset the matching token selects. No match sends the model's own 400 Bad Request
bytes (`Spec.badRequestResponse`, from which all three targets build their copy). The nine tokens
and their offsets are generated from `Spec.allHttpMethods`, whose exhaustiveness over
`Stdlib.Http11.Method` is proved structurally by `Spec.mem_allHttpMethods` -- so a lowering cannot
fall out of step with the parser's method grammar without that proof breaking.

**What this does NOT make true.** The fully general `∀ (request : ByteArray)` claim is still false;
the method was one reason among several, not the last one. See
`spike4GeneralClaimCounterexamples` below for the surviving reasons, each a checked witness.
-/

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#11-supported-http-11-specification-subset -/
/-- PA17's original falsity witness for the fully-general claim: method `"FOO"` is outside
    `Stdlib.Http11.Method`, so the model answers 400, while every lowering used to answer 200 OK.
    Retained under its original name because the guard below is the checked record of the flip --
    it read `!spike4RouteFixedOnAllTargets ...` before the method-validation fix and reads
    `spike4RouteFixedOnAllTargets ...` after it. -/
def witnessMethodNotValidatedDivergence : String :=
  "FOO / HTTP/1.1\r\nHost: localhost\r\n\r\n"

-- The model's verdict is unchanged: parsing fails, so the honest server answers 400 Bad Request.
#guard parseRequestLine witnessMethodNotValidatedDivergence == none
-- FLIPPED by the method-validation fix (was `!spike4RouteFixedOnAllTargets`): all three targets now
-- agree with the model on this request.
#guard spike4RouteFixedOnAllTargets witnessMethodNotValidatedDivergence

/- REF: docs/STDLIB_HTTP11.md#21-request-line -/
/-- A well-formed request line for a given method and target. -/
def spike4MethodRequest (m : Stdlib.Http11.Method) (path : String) : String :=
  s!"{methodToString m} {path} HTTP/1.1\r\nHost: localhost\r\n\r\n"

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#11-supported-http-11-specification-subset -/
/-- Every one of `Stdlib.Http11.Method`'s nine tokens, on one target path, agrees with the model on
    all three lowerings. This is the coverage that pins defect 2 above: the nine methods span five
    distinct token lengths, so a lowering that reverted to a fixed path offset would fail here for
    seven of the nine rather than passing incidentally. -/
def spike4AllMethodsRouteCorrectly (path : String) : Bool :=
  allHttpMethods.all (fun m => spike4RouteFixedOnAllTargets (spike4MethodRequest m path))

#guard spike4AllMethodsRouteCorrectly "/"
#guard spike4AllMethodsRouteCorrectly "/status"

-- Method tokens outside the nine, each answered 400 by the model and now by all three targets.
-- `GETX`/`CONNECTX` specifically pin that the masked compare tests the *delimiter* too, so no
-- token can match as a mere prefix of a longer word; `GE`/`OPTION` pin the truncated-token
-- direction; `get` pins case sensitivity.
#guard spike4RouteFixedOnAllTargets "GETX / HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "CONNECTX / HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "GE / HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "OPTION / HTTP/1.1\r\nHost: localhost\r\n\r\n"
#guard spike4RouteFixedOnAllTargets "get / HTTP/1.1\r\nHost: localhost\r\n\r\n"

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md#4-semantic-trace-equivalence-verifiedprogram-contract -/
/-- **The fully-general `∀ (request : ByteArray)` trace-equivalence claim is still FALSE after the
    method-validation fix, and these are the surviving reasons -- checked, not asserted.**

    PA17's earlier pass recorded the missing method check as the one remaining obstruction. That
    was incomplete. `Stdlib.Http11.parseRequestLine` imposes four obligations on a request line --
    exactly three SP-separated fields, a method in the closed nine-token set, an origin-form
    target, and a literal `HTTP/1.1` version -- and the lowerings now implement the *second* one
    only. Each entry below is a request the model rejects with 400 Bad Request and at least one
    lowering answers differently (200 OK for the ones whose target window still happens to land on
    `"/ "`, 404 for the ones where it lands elsewhere).

    These are recorded as witnesses rather than dissolved into a narrower theorem's hypothesis
    deliberately: implementing the remaining three obligations means putting a real byte-scanning
    request-line parser into the assembly of all three targets, which is a different piece of work
    from validating a fixed set of leading tokens, and pretending the general claim holds by
    excluding these cases silently is exactly the move this file exists to prevent. Any narrowed
    theorem stated over these lowerings must carry a hypothesis that names the excluded class --
    `(parseRequestLine req).isSome`, i.e. "the request line is well-formed" -- with these
    counterexamples cited as the reason the hypothesis is there.

    The list is organised by `Stdlib.Http11.Error` constructor rather than by hand-picked string, so
    that "which classes survive" is answerable by construction instead of by testing whichever
    request someone happened to think of. -/
def spike4GeneralClaimCounterexamples : List (Stdlib.Http11.Error × String × String) :=
  [ (.unsupportedVersion, "version other than HTTP/1.1",
      "GET / HTTP/1.0\r\nHost: localhost\r\n\r\n"),
    (.malformedRequestLine, "two-field request line (no version)",
      "GET /\r\nHost: localhost\r\n\r\n"),
    (.malformedRequestLine, "four-field request line (trailing junk)",
      "GET / HTTP/1.1 extra\r\nHost: localhost\r\n\r\n"),
    (.malformedRequestLine, "doubled SP between method and target",
      "GET  / HTTP/1.1\r\nHost: localhost\r\n\r\n"),
    (.invalidTarget, "absolute-form target (not origin-form)",
      "GET http://example.com/ HTTP/1.1\r\nHost: localhost\r\n\r\n"),
    (.invalidTarget, "target with no leading slash",
      "GET status HTTP/1.1\r\nHost: localhost\r\n\r\n") ]

/- REF: docs/STDLIB_HTTP11.md#31-error-taxonomy -/
/-- The request line as `Stdlib.Http11.parseRequestLine` sees it, kept separate from
    `Spec.parseRequestLine` (which discards the error constructor into `none`) so the witnesses
    below can be pinned to the specific rejection class they stand for. -/
def spike4RequestLineError (req : String) : Option Stdlib.Http11.Error :=
  match Stdlib.Http11.parseRequestLine (((req.splitOn "\r\n").headD "").toUTF8.toList) with
  | .error e => some e
  | .ok _ => none

/- REF: docs/STDLIB_HTTP11.md#31-error-taxonomy -/
/-- The four `Stdlib.Http11.Error` constructors `parseRequestLine` can produce. **Verified by
    inspection of `Stdlib/Http11/Parser.lean`, not by proof**: `parseRequestLine` has exactly three
    `.error` sites (`unknownMethod`, `invalidTarget`, `unsupportedVersion`) plus
    `malformedRequestLine` when `splitThreeFields` returns `none`. `Error` itself has fifteen
    constructors; the other eleven belong to status-line, header and body parsing, which this
    spike's request path never reaches. The `#guard` below confirms all four are genuinely
    reachable; nothing here proves the list is not missing a fifth. -/
def spike4RequestLineErrorTaxonomy : List Stdlib.Http11.Error :=
  [.malformedRequestLine, .unknownMethod, .invalidTarget, .unsupportedVersion]

-- Each witness really does produce the rejection class it is filed under (so a change in how the
-- parser classifies these inputs breaks this file rather than silently mis-labelling the witnesses).
#guard spike4GeneralClaimCounterexamples.all
  (fun (e, _, req) => spike4RequestLineError req == some e)

-- Every constructor in the taxonomy is genuinely reachable: the three unhandled ones via a witness
-- above, `unknownMethod` via `witnessMethodNotValidatedDivergence`.
#guard spike4RequestLineErrorTaxonomy.all (fun e =>
  (spike4GeneralClaimCounterexamples.map (fun (c, _, _) => c)).contains e ||
  spike4RequestLineError witnessMethodNotValidatedDivergence == some e)

-- The completeness statement this section exists for: every way `parseRequestLine` can reject a
-- request line is either the one class the lowerings now implement (`unknownMethod` -- see
-- `witnessMethodNotValidatedDivergence` above, which now passes) or has a live counterexample
-- listed here. Three of the four survive.
#guard spike4RequestLineErrorTaxonomy.all (fun e =>
  e == .unknownMethod ||
  (spike4GeneralClaimCounterexamples.map (fun (c, _, _) => c)).contains e)

-- The model rejects every witness ...
#guard spike4GeneralClaimCounterexamples.all (fun (_, _, req) => parseRequestLine req == none)
-- ... and every one is still a live divergence on all three lowerings. If a future change makes any
-- of these agree, this guard fails and the list must shrink -- the falsity claim above cannot rot
-- into a stale comment the way the route-prefix justification it replaces did.
#guard spike4GeneralClaimCounterexamples.all (fun (_, _, req) => !spike4RouteFixedOnAllTargets req)

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md -/
/-- Widened-buffer, variable-size negative-control regression (N8's "variable sizes ... do not
    crash or corrupt stack state" deliverable). Pairs a garbage/oversized-relative-to-the-old-16-byte-
    buffer request with a well-formed canonical `GET /` request and checks two things about the
    resulting *two-connection* trace: (1) its length is exactly 8 (`listen` once, then
    `accept`/`recv`/`send`/`close` for each of the two connections) -- proving the garbage request's
    recv into the widened 256-byte buffer did not hang, trap, or otherwise prevent the second
    connection from being accepted and served; (2) the trailing 4 events exactly match the expected
    honest response to the canonical request -- proving the garbage request did not corrupt any
    state (buffer content, saved socket descriptors, WSADATA) that the *next* connection depends on.
    This does not assert anything about the garbage connection's own response content (Spec.lean has
    no defined behavior for non-"GET path HTTP/1.1" lines other than 400, which neither lowering
    emits -- a pre-existing, N8-independent gap; see the note above `spike4RouteFixedOnAllTargets`). -/
def spike4SecondConnectionUnaffectedByFirst (garbageReq : String) : Bool :=
  let canonicalRoot := "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"
  let expectedTail : List AnyEvent :=
    [ AnyEvent.of (NetEvent.accept "127.0.0.1"),
      AnyEvent.of (NetEvent.recv canonicalRoot),
      AnyEvent.of (NetEvent.send (formatResponse (routeRequest { method := "GET", path := "/", version := "HTTP/1.1" }))),
      AnyEvent.of (NetEvent.close 101) ]
  let check (trace : List AnyEvent) : Bool :=
    -- `>= 8` is the minimum possible total (listen + 4 events for a teardown-without-send first
    -- connection + 4 events for the second); the exact count of the *first* connection's own
    -- events is deliberately not pinned here (see the doc comment above), only that the trace
    -- ends with precisely the second connection's expected 4 events.
    trace.length >= 8 && trace.drop (trace.length - 4) == expectedTail
  check (runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests [garbageReq, canonicalRoot])) &&
  check (runAsmTrace (Event := AnyEvent) Linux.spike4Instructions (Linux.spike4Executable.loadWithRequests [garbageReq, canonicalRoot])) &&
  check (runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports [garbageReq, canonicalRoot])

#guard spike4SecondConnectionUnaffectedByFirst "X"                                    -- 1 byte
#guard spike4SecondConnectionUnaffectedByFirst (String.ofList (List.replicate 15 'A'))    -- 15 bytes
#guard spike4SecondConnectionUnaffectedByFirst (String.ofList (List.replicate 37 'B'))    -- 37 bytes, deliberately not the canonical valid 37-byte string
#guard spike4SecondConnectionUnaffectedByFirst (String.ofList (List.replicate 120 'C'))   -- 120 bytes
#guard spike4SecondConnectionUnaffectedByFirst (String.ofList (List.replicate 250 'D'))   -- 250 bytes, within 8 bytes of the widened 256-byte buffer's capacity

/- REF: docs/SPIKES/SPIKE4_HTTP_SERVER.md -/
/-- Pins the fixed assembly's own behavior for a `recv`/`read` that returns exactly `0` (the one
    case `docs/SPIKES/SPIKE4_HTTP_SERVER.md`'s defect 2 concerns): the connection is
    closed WITHOUT a `send` event (no uninitialized-buffer content is ever read or transmitted), and
    the following connection is unaffected. See the note above `spike4RouteFixedOnAllTargets` for
    why this is a regression check against the fix's own intended behavior rather than a
    trace-equivalence claim against the honest model (which cannot represent a true zero-byte read
    distinctly from "one more, possibly-empty, logical request"). -/
def spike4EmptyRecvClosesWithoutCorruption : Bool :=
  let emptyOnlyExpected : List AnyEvent :=
    [ AnyEvent.of (NetEvent.listen 8080),
      AnyEvent.of (NetEvent.accept "127.0.0.1"),
      AnyEvent.of (NetEvent.recv ""),
      AnyEvent.of (NetEvent.close 101) ]
  (runAsmTrace (Event := AnyEvent) Windows.spike4Instructions (Windows.spike4Executable.loadWithRequests [""]) == emptyOnlyExpected) &&
  (runAsmTrace (Event := AnyEvent) Linux.spike4Instructions (Linux.spike4Executable.loadWithRequests [""]) == emptyOnlyExpected) &&
  (runWasiTrace spike4WasmInstructions spike4DataSegments ByteArray.empty spike4WasmImports [""] == emptyOnlyExpected.map Inject.inject) &&
  spike4SecondConnectionUnaffectedByFirst ""

#guard spike4EmptyRecvClosesWithoutCorruption

/- REF: docs/SYSTEM_EFFECTS.md#1-universal-environment-oracle-and-syscall-effects -/
instance : EnvironmentLoader HttpRoute where
  loadEnvironment exe r := exe.loadWithRequests [routeRequestStr r]

/- REF: docs/SYSTEM_EFFECTS.md#1-universal-environment-oracle-and-syscall-effects -/
instance : LinuxEnvironmentLoader HttpRoute where
  loadEnvironment exe r := exe.loadWithRequests [routeRequestStr r]

/- REF: docs/SYSTEM_EFFECTS.md#1-universal-environment-oracle-and-syscall-effects -/
instance : WasiEnvironmentLoader HttpRoute where
  loadWasiEnvironment r := (ByteArray.empty, [routeRequestStr r])

/- REF: docs/REVIEW.md#law-8-semantic-spec-to-code-fidelity-anti-facade-law-no-dead-abstractions-or-mock-verification -/
/-- Instantiation of the First-Class Parametric VerifiedProgram contract for Spike 4 on Windows x86_64 across all routing branches.
    NOTE (PA17 domain-honesty finding): despite the `∀ (r : HttpRoute)` shape below satisfying
    `VerifiedProgram`'s literal type signature, this is NOT a Law-9-compliant universal claim over
    the real per-connection request domain -- see the domain-honesty note on `HttpRoute` above and
    the checked malformed-request counterexamples below, which document response mismatches outside
    the three literal requests this contract's proof exercises. Do not
    cite this declaration as evidence Spike 4 has been verified for arbitrary HTTP requests. -/
def spike4WindowsVerifiedProgram : VerifiedProgram HttpRoute AnyEvent where
  name := "spike4_http_server_windows"
  executable := Windows.spike4Executable
  instructions := Windows.spike4Instructions
  spec := routeModelTrace
  traceEquivalence := spike4_windows_route_equivalence

/- REF: docs/REVIEW.md#law-8-semantic-spec-to-code-fidelity-anti-facade-law-no-dead-abstractions-or-mock-verification -/
/-- Instantiation of the First-Class Parametric VerifiedLinuxProgram contract for Spike 4 on Linux x86_64 across all routing branches. -/
def spike4LinuxVerifiedProgram : VerifiedLinuxProgram HttpRoute AnyEvent where
  name := "spike4_http_server_linux"
  executable := Linux.spike4Executable
  instructions := Linux.spike4Instructions
  spec := routeModelTrace
  traceEquivalence := spike4_linux_route_equivalence

/- REF: docs/REVIEW.md#law-8-semantic-spec-to-code-fidelity-anti-facade-law-no-dead-abstractions-or-mock-verification -/
/-- Instantiation of the First-Class Parametric VerifiedWasmProgram contract for Spike 4 on WebAssembly across all routing branches.
    NOTE (PA17 domain-honesty finding): see the identical note on `spike4WindowsVerifiedProgram`
    above -- it applies here unchanged. The old WASI single-byte route-prefix bug is fixed; the
    remaining gap is the malformed-request/error-response mismatch recorded by the checked
    counterexamples above. -/
def spike4WasmVerifiedProgram : VerifiedWasmProgram HttpRoute AnyEvent where
  name := "spike4_http_server_wasm"
  module := spike4WasmModule
  typeSignatures := spike4TypeSignatures
  instructions := spike4WasmInstructions
  dataSegments := spike4DataSegments
  imports := spike4WasmImports
  spec := routeModelTrace
  traceEquivalence := spike4_wasm_route_equivalence

end Spikes.Spike4HttpServer

