/-
Copyright 2026 Craig Tiller

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import Gasm.Compiler.Word
import Gasm.Targets.AArch64.MacroAssembler

namespace Gasm.Compiler.Word.AArch64AAPCS64

open Gasm.Targets.AArch64
open Gasm.Targets.AArch64.MacroAssembler

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def x0 : Gpr := ⟨0, by decide⟩
/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def x1 : Gpr := ⟨1, by decide⟩
/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def x2 : Gpr := ⟨2, by decide⟩
/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def x3 : Gpr := ⟨3, by decide⟩
/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def x9 : Gpr := ⟨9, by decide⟩

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def argReg : Arg → Gpr
  | .a0 => x0
  | .a1 => x1
  | .a2 => x2
  | .a3 => x3

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def argsOfState (state : AArch64MachineState) : Args where
  a0 := state.gprs x0
  a1 := state.gprs x1
  a2 := state.gprs x2
  a3 := state.gprs x3

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def lowerAtom (destination : Gpr) : Atom → Segment
  | .arg index => mov destination (argReg index)
  | .const value => loadImm destination value

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def lowerCombine : BinOp → Segment
  | .add => add x0 x0 x9
  | .sub => sub x0 x0 x9
  | .bitAnd => and x0 x0 x9

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
abbrev Program := List Segment

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
/-- Lower the only two portable shapes generated by `compileExpr`. The binary case evaluates the
    right atom into X9 before overwriting argument/result register X0 with the left atom. -/
def lowerPortable : List Op → Program
  | [.load value] => [lowerAtom x0 value]
  | [.load lhs, .combine operation rhs] =>
      [lowerAtom x9 rhs, lowerAtom x0 lhs, lowerCombine operation]
  | _ => []

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def compileMacros (source : Function) : Program :=
  lowerPortable (compileExpr source.body)

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def compileCode (source : Function) : List Instruction :=
  (compileMacros source).flatMap Segment.code

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def compileAssembly (source : Function) : List AnyAArch64Instruction :=
  (compileCode source).map Instruction.emit

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
def compileBytes (source : Function) : ByteArray :=
  serialize (compileCode source)

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private def replaceLane (current : UInt64) (lane : Nat) (value : UInt16) : UInt64 :=
  UInt64.ofBitVec <|
    (current.toBitVec &&&
      ~~~(((BitVec.allOnes 16).setWidth 64) <<< (lane * 16))) |||
    (value.toBitVec.setWidth 64 <<< (lane * 16))

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem materialize_eq (value : UInt64) :
    replaceLane
      (replaceLane
      (replaceLane value.toUInt16.toUInt64 1 (value >>> 16).toUInt16)
        2 (value >>> 32).toUInt16)
      3 (value >>> 48).toUInt16 = value := by
  rw [← UInt64.toBitVec_inj]
  simp only [replaceLane, UInt64.toBitVec_ofBitVec]
  apply BitVec.eq_of_getLsbD_eq_iff.mpr
  intro index inRange
  by_cases lane0 : index < 16
  · have below32 : index < 32 := by omega
    have below48 : index < 48 := by omega
    simp only [BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_not,
      BitVec.getLsbD_shiftLeft, BitVec.getLsbD_setWidth,
      BitVec.getLsbD_allOnes]
    simp only [UInt64.toBitVec_toUInt16, UInt16.toBitVec_toUInt64,
      UInt64.toBitVec_shiftRight]
    simp [BitVec.getLsbD_setWidth, lane0, below32,
      below48, inRange]
  by_cases lane1 : index < 32
  · have offset16 : index - 16 < 16 := by omega
    have offset16Range : index - 16 < 64 := by omega
    have restore16 : 16 + (index - 16) = index := by omega
    have below48 : index < 48 := by omega
    simp only [BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_not,
      BitVec.getLsbD_shiftLeft, BitVec.getLsbD_setWidth,
      BitVec.getLsbD_allOnes]
    simp only [UInt64.toBitVec_toUInt16, UInt16.toBitVec_toUInt64,
      UInt64.toBitVec_shiftRight]
    simp [BitVec.getLsbD_setWidth, lane0, lane1,
      offset16, offset16Range, restore16, below48, inRange]
  by_cases lane2 : index < 48
  · have offset16Not : ¬index - 16 < 16 := by omega
    have offset16Range : index - 16 < 64 := by omega
    have offset32 : index - 32 < 16 := by omega
    have offset32Range : index - 32 < 64 := by omega
    have restore32 : 32 + (index - 32) = index := by omega
    simp only [BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_not,
      BitVec.getLsbD_shiftLeft, BitVec.getLsbD_setWidth,
      BitVec.getLsbD_allOnes]
    simp only [UInt64.toBitVec_toUInt16, UInt16.toBitVec_toUInt64,
      UInt64.toBitVec_shiftRight]
    simp [BitVec.getLsbD_setWidth, lane0, lane1, lane2,
      offset16Not, offset16Range, offset32, offset32Range, restore32, inRange]
  · have offset16Not : ¬index - 16 < 16 := by omega
    have offset16Range : index - 16 < 64 := by omega
    have offset32Not : ¬index - 32 < 16 := by omega
    have offset32Range : index - 32 < 64 := by omega
    have offset48 : index - 48 < 16 := by omega
    have offset48Range : index - 48 < 64 := by omega
    have restore48 : 48 + (index - 48) = index := by omega
    simp only [BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_not,
      BitVec.getLsbD_shiftLeft, BitVec.getLsbD_setWidth,
      BitVec.getLsbD_allOnes]
    simp only [UInt64.toBitVec_toUInt16, UInt16.toBitVec_toUInt64,
      UInt64.toBitVec_shiftRight]
    simp [BitVec.getLsbD_setWidth, lane0, lane1, lane2,
      offset16Not, offset16Range, offset32Not, offset32Range, offset48,
      offset48Range, restore48, inRange]

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem replaceLane1_eq (current : UInt64) (value : UInt16) :
    (current &&& ~~~((0xFFFF : UInt64) <<< 16)) ||| (value.toUInt64 <<< 16) =
      replaceLane current 1 value := by
  rw [← UInt64.toBitVec_inj]
  rfl

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem replaceLane2_eq (current : UInt64) (value : UInt16) :
    (current &&& ~~~((0xFFFF : UInt64) <<< 32)) ||| (value.toUInt64 <<< 32) =
      replaceLane current 2 value := by
  rw [← UInt64.toBitVec_inj]
  rfl

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem replaceLane3_eq (current : UInt64) (value : UInt16) :
    (current &&& ~~~((0xFFFF : UInt64) <<< 48)) ||| (value.toUInt64 <<< 48) =
      replaceLane current 3 value := by
  rw [← UInt64.toBitVec_inj]
  rfl

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem loadImm_result (destination : Gpr) (value : UInt64)
    (state : AArch64MachineState) :
    (runLocalSteps (loadImm destination value).code state).gprs destination = value := by
  let lane0 : MovWideLane := ⟨0, by decide⟩
  let lane1 : MovWideLane := ⟨1, by decide⟩
  let lane2 : MovWideLane := ⟨2, by decide⟩
  let lane3 : MovWideLane := ⟨3, by decide⟩
  rw [show (loadImm destination value).code =
      (movz destination value.toUInt16 lane0).code ++
      (movk destination (value >>> 16).toUInt16 lane1).code ++
      (movk destination (value >>> 32).toUInt16 lane2).code ++
      (movk destination (value >>> 48).toUInt16 lane3).code by rfl]
  simp only [runLocalSteps_append]
  rw [movk_result, movk_result, movk_result, movz_result]
  have shift0 : ((lane0.encoding.toUInt64 &&& 3) * 16) = 0 := by decide
  have shift1 : ((lane1.encoding.toUInt64 &&& 3) * 16) = 16 := by decide
  have shift2 : ((lane2.encoding.toUInt64 &&& 3) * 16) = 32 := by decide
  have shift3 : ((lane3.encoding.toUInt64 &&& 3) * 16) = 48 := by decide
  rw [shift0, shift1, shift2, shift3]
  simp only [UInt64.shiftLeft_zero]
  simp only [replaceLane1_eq, replaceLane2_eq, replaceLane3_eq]
  exact materialize_eq value

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
theorem lowerAtom_correct (destination : Gpr) (atom : Atom)
    (state : AArch64MachineState) :
    (runLocalSteps (lowerAtom destination atom).code state).gprs destination =
      atom.eval (argsOfState state) := by
  cases atom with
  | arg index =>
    cases index with
    | a0 => simpa [lowerAtom, argReg, argsOfState, Atom.eval, Args.get] using
        mov_result destination x0 state
    | a1 => simpa [lowerAtom, argReg, argsOfState, Atom.eval, Args.get] using
        mov_result destination x1 state
    | a2 => simpa [lowerAtom, argReg, argsOfState, Atom.eval, Args.get] using
        mov_result destination x2 state
    | a3 => simpa [lowerAtom, argReg, argsOfState, Atom.eval, Args.get] using
        mov_result destination x3 state
  | const value =>
    simpa [lowerAtom, Atom.eval] using loadImm_result destination value state

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
theorem lowerAtom_preservesGpr (destination register : Gpr)
    (different : register ≠ destination) (atom : Atom) (state : AArch64MachineState) :
    (runLocalSteps (lowerAtom destination atom).code state).gprs register =
      state.gprs register := by
  cases atom with
  | arg index =>
    apply (lowerAtom destination (.arg index)).preservesGpr
    change register ∉ [destination]
    simpa using different
  | const value =>
    apply (lowerAtom destination (.const value)).preservesGpr
    change register ∉ [destination, destination, destination, destination]
    simp [different]

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem lowerAtomX9_preservesArgs (atom : Atom) (state : AArch64MachineState) :
    argsOfState (runLocalSteps (lowerAtom x9 atom).code state) = argsOfState state := by
  apply Args.ext <;>
    simp only [argsOfState] <;>
    apply lowerAtom_preservesGpr <;>
    decide

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem lowerCombine_correct (operation : BinOp) (state : AArch64MachineState) :
    (runLocalSteps (lowerCombine operation).code state).gprs x0 =
      operation.eval (state.gprs x0) (state.gprs x9) := by
  cases operation with
  | add => exact add_result x0 x0 x9 state
  | sub => exact sub_result x0 x0 x9 state
  | bitAnd => exact and_result x0 x0 x9 state

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
private theorem lowerCombine_preservesGpr (operation : BinOp) (register : Gpr)
    (different : register ≠ x0) (state : AArch64MachineState) :
    (runLocalSteps (lowerCombine operation).code state).gprs register =
      state.gprs register := by
  cases operation with
  | add =>
    apply (lowerCombine .add).preservesGpr
    change register ∉ [x0]
    simpa using different
  | sub =>
    apply (lowerCombine .sub).preservesGpr
    change register ∉ [x0]
    simpa using different
  | bitAnd =>
    apply (lowerCombine .bitAnd).preservesGpr
    change register ∉ [x0]
    simpa using different

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
theorem compileCode_correct (source : Function) (state : AArch64MachineState) :
    (runLocalSteps (compileCode source) state).gprs x0 =
      source.fn (argsOfState state) := by
  rw [source.implements]
  cases bodyEq : source.body with
  | atom value =>
    simpa [compileCode, compileMacros, compileExpr, lowerPortable, bodyEq, Expr.eval] using
      lowerAtom_correct x0 value state
  | binary operation lhs rhs =>
    simp only [compileCode, compileMacros, compileExpr, lowerPortable, bodyEq,
      List.flatMap_cons, List.flatMap_nil, List.append_nil, runLocalSteps_append]
    let afterRhs := runLocalSteps (lowerAtom x9 rhs).code state
    let afterLhs := runLocalSteps (lowerAtom x0 lhs).code afterRhs
    rw [lowerCombine_correct operation afterLhs]
    rw [lowerAtom_correct x0 lhs afterRhs]
    rw [lowerAtom_preservesGpr x0 x9 (by decide) lhs afterRhs]
    rw [lowerAtom_correct x9 rhs state]
    rw [lowerAtomX9_preservesArgs rhs state]
    rfl

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
theorem compileCode_preservesGpr (source : Function) (state : AArch64MachineState)
    (register : Gpr) (notResult : register ≠ x0) (notScratch : register ≠ x9) :
    (runLocalSteps (compileCode source) state).gprs register = state.gprs register := by
  cases bodyEq : source.body with
  | atom value =>
    simpa [compileCode, compileMacros, compileExpr, lowerPortable, bodyEq] using
      lowerAtom_preservesGpr x0 register notResult value state
  | binary operation lhs rhs =>
    simp only [compileCode, compileMacros, compileExpr, lowerPortable, bodyEq,
      List.flatMap_cons, List.flatMap_nil, List.append_nil, runLocalSteps_append]
    rw [lowerCombine_preservesGpr operation register notResult,
      lowerAtom_preservesGpr x0 register notResult,
      lowerAtom_preservesGpr x9 register notScratch]

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
theorem compileAssembly_controlFlowFree (source : Function)
    (instruction : AnyAArch64Instruction) (member : instruction ∈ compileAssembly source) :
    ControlFlowFree instruction := by
  simp only [compileAssembly, List.mem_map] at member
  obtain ⟨selected, _, rfl⟩ := member
  exact selected.controlFlowFree

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
/-- Proof-producing local frontend output for the selected AAPCS64 register realization. This is
    not platform execution evidence: it has no RET, stack frame, callable boundary, artifact
    identity, fetch/lookup, fuel, host interception, admissibility, or `VerifiedProgram` claim. -/
structure LocalCertificate (source : Function) where
  portable : List Op
  macros : Program
  code : List Instruction
  instructions : List AnyAArch64Instruction
  codeBytes : ByteArray
  portable_eq : portable = compileExpr source.body
  portableCorrect : ∀ args, run portable args = source.fn args
  macros_eq : macros = lowerPortable portable
  code_eq : code = macros.flatMap Segment.code
  instructions_eq : instructions = code.map Instruction.emit
  codeBytes_eq : codeBytes = serialize code
  emittedBytes_eq : codeBytes = serializeEmitted instructions
  localResult : ∀ state,
    (runLocalSteps code state).gprs x0 = source.fn (argsOfState state)
  preservesInputs : ∀ state,
    (runLocalSteps code state).gprs x1 = state.gprs x1 ∧
    (runLocalSteps code state).gprs x2 = state.gprs x2 ∧
    (runLocalSteps code state).gprs x3 = state.gprs x3
  preservesMemory : ∀ state, (runLocalSteps code state).memory = state.memory
  preservesSp : ∀ state, (runLocalSteps code state).sp = state.sp
  preservesNzcv : ∀ state, (runLocalSteps code state).nzcv = state.nzcv
  preservesFault : ∀ state, (runLocalSteps code state).fault = state.fault
  preservesTerminated : ∀ state,
    (runLocalSteps code state).terminated = state.terminated
  pcAdvance : ∀ state,
    (runLocalSteps code state).pc = state.pc + localCodeSize code
  clobberedGprs : List Gpr
  clobberedGprs_eq : clobberedGprs = [x0, x9]
  preservesGpr : ∀ state register, register ∉ clobberedGprs →
    (runLocalSteps code state).gprs register = state.gprs register
  controlFlowFree : ∀ instruction ∈ instructions, ControlFlowFree instruction

/- REF: docs/MACRO_ASSEMBLER.md#aarch64-aapcs64-backend -/
/-- Generate exactly the feature-applicable local certificate. Final placement and execution
    premises remain target/linker-owned inputs to the sole platform verification authority. -/
def lower (source : Function) : LocalCertificate source where
  portable := compileExpr source.body
  macros := compileMacros source
  code := compileCode source
  instructions := compileAssembly source
  codeBytes := compileBytes source
  portable_eq := rfl
  portableCorrect := compileFunction_correct source
  macros_eq := rfl
  code_eq := rfl
  instructions_eq := rfl
  codeBytes_eq := rfl
  emittedBytes_eq := serialize_eq_serializeEmitted (compileCode source)
  localResult := compileCode_correct source
  preservesInputs := by
    intro state
    exact ⟨compileCode_preservesGpr source state x1 (by decide) (by decide),
      compileCode_preservesGpr source state x2 (by decide) (by decide),
      compileCode_preservesGpr source state x3 (by decide) (by decide)⟩
  preservesMemory := runLocalSteps_preservesMemory (compileCode source)
  preservesSp := runLocalSteps_preservesSp (compileCode source)
  preservesNzcv := runLocalSteps_preservesNzcv (compileCode source)
  preservesFault := runLocalSteps_preservesFault (compileCode source)
  preservesTerminated := runLocalSteps_preservesTerminated (compileCode source)
  pcAdvance := runLocalSteps_pc (compileCode source)
  clobberedGprs := [x0, x9]
  clobberedGprs_eq := rfl
  preservesGpr := by
    intro state register notClobbered
    simp only [List.mem_cons, not_or, List.not_mem_nil] at notClobbered
    exact compileCode_preservesGpr source state register notClobbered.1 notClobbered.2.1
  controlFlowFree := compileAssembly_controlFlowFree source

end Gasm.Compiler.Word.AArch64AAPCS64
